name: auto-upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  auto-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Upgrade
        run: |
          cargo run -p upgrade
          cargo run -p generator
          cargo update jay-ash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update Vulkan-Headers
          title: Update Vulkan-Headers
          body: ''
          branch: bot/update-protocols
          base: master
      - name: Notify failed build
        uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b # v1.2
        if: failure()
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          label-name: 'auto-update'
          title-template: 'Auto Update Failed'
