name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo check --workspace --all-targets --all-features

  check_msrv:
    name: Check ash MSRV (1.90.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
      - name: Check ash
        run: cargo check -p jay-ash --all-features
      - name: Check ash with no_std
        run: cargo check -p jay-ash --no-default-features

  generated:
    name: Generated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Checkout submodule
        run: git submodule update --init
      - name: Run generator
        run: cargo run -p generator
      - name: Diff autogen result
        run: test -z "$(git status --porcelain)" || (echo "::error::Generated files are different, please regenerate with cargo run -p generator!"; git diff; false)

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install Vulkan loader
        run: sudo apt-get install libvulkan-dev
      - uses: actions/checkout@v6
      - name: Test all targets
        run: cargo test --workspace --all-features --all-targets
      - name: Test docs
        run: cargo test --workspace --all-features --doc

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-ios
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Add Rust target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: Clippy lint without features
        run: cargo clippy --target ${{ matrix.target }} --no-default-features -- -D warnings
      - name: Clippy lint with all features
        run: cargo clippy --target ${{ matrix.target }} --workspace --all-targets --all-features -- -D warnings
      - name: Clippy lint with default features
        run: cargo clippy --target ${{ matrix.target }} --workspace --all-targets -- -D warnings

  docs:
    name: Build-test docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Document all crates
        env:
          RUSTDOCFLAGS: -Dwarnings
        run: cargo doc --all --all-features --no-deps --document-private-items
